__title__ = 'Mayan EDMS'
__version__ = '4.6.5'
__build__ = 0x040603
__build_string__ = 'v4.6.4-38-g4a37f221b36_Wed Aug 6 05:37:35 2025 -0400'
__django_version__ = '4.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2025 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
